spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conference
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rla363636!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      show-sql: true
      open-in-view: false
    properties:
      hibernate:
        format_sql: true
