spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conference
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!@

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      open-in-view: false
    properties:
      hibernate:
        format_sql: true
