spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conference
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rla363636!

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create-drop
        show-sql: true
        open-in-view: false

