spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect # ? ?? ?? (MySQL? ?? `MySQL8Dialect`)
        default_batch_fetch_size: 50 # 1 ~ 1000 ? ?? 500?? ??. ?? ?? ?? ??? ??.


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mapjiri
    username: root
    password: rla363636!
